version: '3.5'

services:
    geekmania-catalog-api:
        container_name: geekmania-catalog-api
        build: 
            context: .
            dockerfile: "src/Catalog/CatalogApi/Dockerfile"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production 
        restart: always
        ports:
            - "8042:80"
            - "9042:443"
        networks: 
            - geekmania_networks

    geekmania-catalog-reading-api:
        container_name: geekmania-catalog-reading-api
        build: 
            context: .
            dockerfile: "src/Catalog/CatalogApiReading/Dockerfile"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        restart: always
        ports:
            - "8043:80"
            - "9043:443"
        networks: 
            - geekmania_networks
            
    geekmania-rabbitmq:
        image: rabbitmq:3-management
        container_name: geekmania-rabbitmq
        hostname: geekmania-rabbitmq
        ports:
            - 9043:15672
            - 5673:5672
            - 25676:25676
        networks: 
            - geekmania_networks
        volumes:
            - /docker/volumes/geekmania-rabbitmq:/var/lib/rabbitmq
        environment:
            - RABBITMQ_ERLANG_COOKIE=geekmania-guedes
            - RABBITMQ_DEFAULT_USER=mqgeek
            - RABBITMQ_DEFAULT_PASS=Kennyguedes@

networks: 
    geekmania_networks:
        driver: bridge